### ISSUE TITLE
Typos in doc block for Guzzle and Slim factories

### ISSUE THREAD

**Issue by partnerizemark** [middlewares/utils#15]
https://github.com/middlewares/utils/blob/7ad4e140ea96ba667603ac6a3f5650ccb838f3de/src/Factory/GuzzleFactory.php#L29

https://github.com/middlewares/utils/blob/7ad4e140ea96ba667603ac6a3f5650ccb838f3de/src/Factory/SlimFactory.php#L30

**Comment by oscarotero** [comment]
Fixed. Thanks!
