### ISSUE TITLE
zend-diactoros is deprecated by laminas/laminas-diactoros.

### ISSUE THREAD

**Issue by DarkMukke** [middlewares/utils#20]
https://github.com/zendframework/zend-diactoros states :

> ## Repository abandoned 2019-12-31
>
> This repository has moved to laminas/laminas-diactoros.

We should replace 

    const DIACTOROS = [
        'request' => 'Zend\Diactoros\RequestFactory',
        'response' => 'Zend\Diactoros\ResponseFactory',
        'serverRequest' => 'Zend\Diactoros\ServerRequestFactory',
        'stream' => 'Zend\Diactoros\StreamFactory',
        'uploadedFile' => 'Zend\Diactoros\UploadedFileFactory',
        'uri' => 'Zend\Diactoros\UriFactory',
    ];

with 

    const DIACTOROS = [
        'request' => 'Laminas\Diactoros\RequestFactory',
        'response' => 'Laminas\Diactoros\ResponseFactory',
        'serverRequest' => 'Laminas\Diactoros\ServerRequestFactory',
        'stream' => 'Laminas\Diactoros\StreamFactory',
        'uploadedFile' => 'Laminas\Diactoros\UploadedFileFactory',
        'uri' => 'Laminas\Diactoros\UriFactory',
    ];

**Comment by DarkMukke** [comment]
for now the work around is to set the `ResponseFactory` manually for each middleware

eg (using Harmony)

    ->addMiddleware(
        new Recaptcha( 
            $c->get('recaptcha-secret'), new Laminas\Diactoros\ResponseFactory
        )
    )

**Comment by oscarotero** [comment]
thanks for notify and fix this. I just released a new version with this change.
