### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by arokettu** [middlewares/utils#22]
Tests seem to pass but dev dependencies need to be reviewed

**Comment by oscarotero** [comment]
Hi, thanks for the warning.
I don't have PHP8 installed in my computer yet, so I cannot test it. If you want to work in a pull request, it would be great. If not, don't worry, I'll fix it.
Thanks.

**Comment by arokettu** [comment]
I don't want to work here because it involves decisions that involve maintainer's comfort

Here is the list of blockers after upgrade of outdated libraries:

```
$ composer why-not php 8                
friendsofphp/php-cs-fixer       v2.16.7     requires  php (^7.1)  
guzzlehttp/psr7                 2.0.x-dev   requires  php (^7.2)  
oscarotero/php-cs-fixer-config  v1.0.1      requires  php (^7.2)  
slim/psr7                       1.2.0       requires  php (^7.2)  
sunrise/http-header             v1.0.9      requires  php (^7.1)  
sunrise/http-message            v1.3.0      requires  php (^7.1)  
sunrise/http-server-request     v1.0.12     requires  php (^7.1)  
sunrise/stream                  v1.0.21     requires  php (^7.1)  
sunrise/uri                     v1.1.0      requires  php (^7.1)
```

Here is my pr for whoops: https://github.com/middlewares/whoops/pull/9

**Comment by oscarotero** [comment]
Ok, understood. Those are all dev dependencies, so I think it should be easy to fix. I'll work on that.
Thanks!
