### ISSUE TITLE
String conversion problem in CallableHandler

### ISSUE THREAD

**Issue by itsjavi** [middlewares/utils#4]
In case the callable returns a non string-friendly value (not scalars, arrays, objects without __toString, etc) this line will produce a warning:
https://github.com/middlewares/utils/blob/master/src/CallableHandler.php#L36

In that case we should throw an exception, because it's not responsibility of this class to make decisions about how to convert them to string, or delegate that (somehow) to next middleware like "I don't know what to do with this".

**Comment by oscarotero** [comment]
I'm agree about avoid warnings, but not sure if throw exceptions.
A simple solution could be check whether the return value is strictly a string, and if not, do nothing.
This makes the signature more strict and easy to understand: the returned value can be a ResponseInterface or a string. Other types will be ignored. If the user want to append content to the response, just need to be sure that the return type is a string: `return (string) $content; `

what do you think? Do you want to work in a pull request?

**Comment by itsjavi** [comment]
I think that silently ignoring what's going on by doing nothing will make things harder to debug and understand for the consumers of this class.
If `$return` is neither a response or scalar, then I would just return it and let it fail or be handled in an upper level.
If the developer decided to return other types, they may have some other reason for that, like having another layer that will take care of converting the result into a proper Response object.

I could provide a pull request for that if you agree

**Comment by oscarotero** [comment]
The problem I see is how to easily detect if something can be stringified without put a lot of code. (object without __string, resources, etc...)
But this can be better discussed with some code at sight.

**Comment by oscarotero** [comment]
Well, that was easier than I throught (I didn't know `is_scalar`), so now throws an `UnexpectedValueException` if the value cannot be converted to a string.

**Comment by itsjavi** [comment]
@oscarotero that's great, thanks for taking care of it
